title: "EmriDev"
email: emrireal@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: ''
favicon: 'assets/images/favicon.ico'
author: Emri
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: M Riduan
    display_name: Emri
    avatar: 'assets/images/sal.png'
    email: emrireal@gmail.com
    web: https://emridev.github.io/
    twitter: https://www.facebook.com/cakdumek
    description: "This is the author box. Write a short description of the author here."
  
# Social
social:
  instagram: https://www.instagram.com/emri.id/
  facebook: https://www.facebook.com/cakdumek
  
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
